### PR TITLE
fix: broken hot restart when using native_event_loop (macOS)

### LINKED ISSUE #74: [Bug Report] native_event_loop: Hot restart interrupts the listening of events
This is a minor bug, as it does not affect an app in production, only in development.

When the `native_event_loop` is used, if we hot restart the app in dev mode the mpv events are no longer listened by the `Player`.

### PR DESCRIPTION
**Pull request by birros**
Fix #74

### CODE REVIEW

**Comment by birros** [comment]
I only removed the global `send_port`, but I can do the same for `post_c_object` if you want?

File: media_kit_native_event_loop/src/media_kit_native_event_loop.cc [hunk 1]
```diff
@@ -22,12 +22,9 @@ void MediaKitEventLoopHandler::Register(int64_t handle,
     post_c_object_ =
         reinterpret_cast<bool (*)(Dart_Port, Dart_CObject*)>(post_c_object);
   }
-  if (send_port_ == -1) {
-    send_port_ = send_port;
-  }
 
   auto context = reinterpret_cast<mpv_handle*>(handle);
-  std::thread([this, context]() {
+  std::thread([this, context, send_port]() {
```
Comment (alexmercerind) [inline media_kit_native_event_loop/src/media_kit_native_event_loop.cc:27]:
```suggestion
  std::thread([=]() {
```

Should work AFAIK.

**Comment by alexmercerind** [comment]
> I only removed the global `send_port`, but I can do the same for `post_c_object` if you want?

Sure, let's remove them all. And this comment too:

https://github.com/alexmercerind/media_kit/blob/c5b85d1e679b733ff193c41ada52546034133a17/media_kit_native_event_loop/src/media_kit_native_event_loop.cc#L19-L20

🙏
